### ISSUE TITLE
Unable to compile at deepin 20 1003

### ISSUE THREAD

**Issue by shenmo7192** [dekzi/dde-store#1]
`/home/sy120zx/Desktop/dde-store/mainwindow.cpp: In member function ‘void MainWindow::initNav()’:
/home/sy120zx/Desktop/dde-store/mainwindow.cpp:128:22: error: ‘qOverload’ was not declared in this scope
     connect(navView, qOverload<const QModelIndex &>(&DListView::currentChanged), this, [ = ] (const QModelIndex &previous) {
                      ^~~~~~~~~
/home/sy120zx/Desktop/dde-store/mainwindow.cpp:128:22: note: suggested alternative: ‘QOverload’
     connect(navView, qOverload<const QModelIndex &>(&DListView::currentChanged), this, [ = ] (const QModelIndex &previous) {
                      ^~~~~~~~~
                      QOverload
/home/sy120zx/Desktop/dde-store/mainwindow.cpp:128:32: error: expected primary-expression before ‘const’
     connect(navView, qOverload<const QModelIndex &>(&DListView::currentChanged), this, [ = ] (const QModelIndex &previous) {
                                ^~~~~
make[3]: *** [CMakeFiles/dde-store.dir/build.make:150：CMakeFiles/dde-store.dir/mainwindow.cpp.o] 错误 1
make[3]: *** 正在等待未完成的任务....
make[3]: 离开目录“/home/sy120zx/Desktop/dde-store/obj-x86_64-linux-gnu”
make[2]: *** [CMakeFiles/Makefile2:76：CMakeFiles/dde-store.dir/all] 错误 2
make[2]: 离开目录“/home/sy120zx/Desktop/dde-store/obj-x86_64-linux-gnu”
make[1]: *** [Makefile:133：all] 错误 2
make[1]: 离开目录“/home/sy120zx/Desktop/dde-store/obj-x86_64-linux-gnu”
dh_auto_build: cd obj-x86_64-linux-gnu && make -j4 returned exit code 2
make: *** [debian/rules:4：build] 错误 `

**Comment by shenmo7192** [comment]
```
/home/sy120zx/Desktop/dde-store/mainwindow.cpp: In member function ‘void MainWindow::initNav()’:
/home/sy120zx/Desktop/dde-store/mainwindow.cpp:128:22: error: ‘qOverload’ was not declared in this scope
     connect(navView, qOverload<const QModelIndex &>(&DListView::currentChanged), this, [ = ] (const QModelIndex &previous) {
                      ^~~~~~~~~
/home/sy120zx/Desktop/dde-store/mainwindow.cpp:128:22: note: suggested alternative: ‘QOverload’
     connect(navView, qOverload<const QModelIndex &>(&DListView::currentChanged), this, [ = ] (const QModelIndex &previous) {
                      ^~~~~~~~~
                      QOverload
/home/sy120zx/Desktop/dde-store/mainwindow.cpp:128:32: error: expected primary-expression before ‘const’
     connect(navView, qOverload<const QModelIndex &>(&DListView::currentChanged), this, [ = ] (const QModelIndex &previous) {
                                ^~~~~
make[3]: *** [CMakeFiles/dde-store.dir/build.make:150：CMakeFiles/dde-store.dir/mainwindow.cpp.o] 错误 1
make[3]: *** 正在等待未完成的任务....
make[3]: 离开目录“/home/sy120zx/Desktop/dde-store/obj-x86_64-linux-gnu”
make[2]: *** [CMakeFiles/Makefile2:76：CMakeFiles/dde-store.dir/all] 错误 2
make[2]: 离开目录“/home/sy120zx/Desktop/dde-store/obj-x86_64-linux-gnu”
make[1]: *** [Makefile:133：all] 错误 2
make[1]: 离开目录“/home/sy120zx/Desktop/dde-store/obj-x86_64-linux-gnu”
dh_auto_build: cd obj-x86_64-linux-gnu && make -j4 returned exit code 2
make: *** [debian/rules:4：build] 错误 
```

**Comment by ghost** [comment]
Thanks for reporting! I'll try to reproduce this on Ubuntu or Arch, [Currently the Deepin distrobution isn't supported](https://github.com/dekzi/dde-store#deepin-distro), so if this is a Deepin specific problem, it may not be fixed.

**Comment by ghost** [comment]
Can't reproduce on Ubuntu or Arch. Looks like an issue with Deepin's Qt version being older. If the issue is reproducible on Ubuntu or Arch, I will reopen this. Thanks!
