### ISSUE TITLE
Icons are very pixelated

### ISSUE THREAD

**Issue by scroom** [dekzi/dde-store#15]
Just installed the DDE store. What a great project! One thing struck me right away when I first opened the store: The icons of the individual apps to be installed are pixelated. This looks better in Gnome, for example, so far. Resolution is 2560*1440, scaling is set to 1,25.
I'm using UbuntuDDE 20.10.
Here comes a screenshot:
![Bildschirmfoto vom 2021-01-10 23-27-57](https://user-images.githubusercontent.com/5347731/104137228-8e74fd00-539b-11eb-891f-937ba3ce4e46.png)

**Comment by ghost** [comment]
Thanks for reporting this! Seems like it may be an issue with the scaling. I'll take a look at it with 1.25 scaling on my own machine and see if I can reproduce this.

**Comment by ghost** [comment]
Reproducible, found the issue, plus it's a super super easy fix!

Before:
![Screen Capture_select-area_20210110151133](https://user-images.githubusercontent.com/56656996/104138100-aece9880-5356-11eb-8052-02189dc23550.png)

After:
![Screen Capture_select-area_20210110151113](https://user-images.githubusercontent.com/56656996/104138095-a4ac9a00-5356-11eb-8991-4fc0ee3db657.png)

Thanks for the report!

**Comment by scroom** [comment]
Wow! You are fast!

**Comment by ghost** [comment]
> Wow! You are fast!

Hah, that was just a 1 line fix, but thank you!
