### ISSUE TITLE
the app doesn't open on ubuntu 21.04

### ISSUE THREAD

**Issue by Stem-LG** [dekzi/dde-store#23]
clicking on the app drom the ment does nothing ( and it has no icon btw )
& launching from terminal shows this

![image](https://user-images.githubusercontent.com/37732484/130318710-5963d395-28d6-4d98-83d5-75500e26437e.png)

**Comment by ghost** [comment]
Hey there,
DDE Store is designed for the Deepin Desktop Environment and probably won't play very nice with any other DE. DDE Store would be a good option if you're running UbuntuDDE, but for normal Ubuntu there's just no need for it. I'd recommenced using GNOME Software, which is preinstalled on Ubuntu anyways.
