### ISSUE TITLE
Open-euler 22.03 can not compile: DListView not found

### ISSUE THREAD

**Issue by terwer** [dekzi/dde-store#26]
# My environment
➜  dde-store git:(master) ✗ neofetch
terwer@plopeneuler 
------------------ 
 OS: openEuler 22.03 LTS x86_64 
Host: Parallels Software International Inc. Parallels Virtual Platform 
Kernel: 5.10.0-60.32.0.61.oe2203.x86_64 
Uptime: 30 mins 
Shell: zsh 5.8 
Resolution: 1792x1004 
Terminal: /dev/pts/1 
 CPU: Intel i9-9980HK (8) @ 2.400GHz 
GPU: Virtio: Virtio GPU 
Memory: 1265MiB / 15482MiB 

# Error msg
➜  dde-store git:(master) ✗ 
➜  dde-store git:(master) ✗ cmake .
-- Configuring done
-- Generating done
-- Build files have been written to: /code/dde-store
➜  dde-store git:(master) ✗ sudo make install 
......
[ 64%] Building CXX object CMakeFiles/dde-store.dir/dde-store_autogen/mocs_compilation.cpp.o
In file included from /code/dde-store/dde-store_autogen/EWIEGA46WW/moc_mainwindow.cpp:10,
                 from /code/dde-store/dde-store_autogen/mocs_compilation.cpp:6:
/code/dde-store/dde-store_autogen/EWIEGA46WW/../../mainwindow.h:5:10: 致命错误：DListView：没有那个文件或目录
    5 | #include <DListView>
      |          ^~~~~~~~~~~
编译中断。
make[2]: *** [CMakeFiles/dde-store.dir/build.make:226：CMakeFiles/dde-store.dir/dde-store_autogen/mocs_compilation.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:101：CMakeFiles/dde-store.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2

**Comment by ghost** [comment]
Hi!

Just a heads up - missing headers like this is practically never an issue with the software you're compiling, but rather just missing dependencies on your system, and this case is no different.

The dependencies in the [building section](https://github.com/dekzi/dde-store#building-from-source) of the README are required on every distro, I marked that section as "Ubuntu" as those are the package names for Ubuntu specifically - for other distros, you'll have to find the equivalent packages. I don't really have the time to list the correct package names for every possible package manager and repo.

You're most likely missing libdtkgui (the -dev or -devel version), so you can try using that as a query in your package manager's search function.

I'm closing this as this isn't an issue with DDE Store, but feel free to let me know if you've solved this!
